### ISSUE TITLE
Show SDM toggle updates

### ISSUE THREAD

**Issue by LanesGood** [EpiPandit/atlas-arena#11]
When the “Show rodent reservoirs distribution” (SDM) toggle switch is OFF:
- [x] All Species Distribution Maps (SDM) should be removed from the map
- [x] All "Reservoir Species" checkboxes should be set to off and disabled

**Comment by LanesGood** [comment]
@yunica was this changed with the partner? I now see "Show viral hotspot" as a toggle.

**Comment by yunica** [comment]
Yes, this change was made because the partner wanted to show the `hotspots` and the `SDM` at the same time.
We can better adapt the description.

**Comment by LanesGood** [comment]
Noting - we should change this back to "Show Species Distribution Maps"
