### ISSUE TITLE
Explore yaml/code/git-based configs

### ISSUE THREAD

**Issue by LanesGood** [EpiPandit/atlas-arena#5]
@yunica @rub21 As we start to understand how the AtlasArena application data is structured, we will also want to lay out a few proposed ideas for how models, data, and content can be updated and managed by the UC Davis team.

Our proposal and past projects use a YAML-based approach. Do you think this is feasible for this application? What would the requirements for setting up YAML config be, and does the data and models you're investigating lend itself to this approach?

Are there any other approaches or methods you would recommend or prefer based on the datasets and models?

**Comment by yunica** [comment]
@LanesGood , the structure provided by the yaml files seems to be sufficient to manage the model data, configuration parameters and static information, we can separate them into a folder so that the UC Davis team can update them.

**Comment by Rub21** [comment]
@LanesGood It seems YAML files have already worked for past projects. Could you share a couple of those YAML files so we can review them and adapt them for the AtlasArena project?

**Comment by LanesGood** [comment]
@Rub21 this seems to be under your area of expertise, so I defer to your leadership here. Areas where I know you have lead these efforts include Afghanistan Elections.

Here's a link from Afghanistan, where the API was configured by a YAML file:
- https://nditech.github.io/af-elections-docs/docs/elections/config <= config instructions
- https://github.com/nditech/af-elections-api/blob/master/data/2014-presidential/index.yml <= example YML file
