### ISSUE TITLE
Allow min-zoom to 0

### ISSUE THREAD

**Issue by LanesGood** [EpiPandit/atlas-arena#9]
Users should not be restricted from zooming out.

**Comment by yunica** [comment]
I think setting a zoom limit of `2 `works better than zoom `0`.


- Zoom 0, depending on the screen resolution, the continents can be doubled.
![2024-10-17_23-29](https://github.com/user-attachments/assets/fa14addb-5610-4534-b2bb-f7afc359d965)

- Zoom 2.
![2024-10-17_23-29_1](https://github.com/user-attachments/assets/232b02e2-d246-42fb-a3ee-65246f23a55d)
